// Articles 02 à 04 (cartes existantes du blog).
export const ARTICLES_A = [
  {
    slug: 'ugc-ads-creas-statiques',
    category: 'Creative Strategy',
    readTime: 6,
    date: '2026-02-05',
    title: 'UGC Ads : pourquoi vos créas statiques ne convertissent plus',
    metaTitle: 'UGC Ads : pourquoi vos créas statiques ne convertissent plus',
    description: 'Vos visuels produits sont beaux mais ne vendent pas ? Voici les mécaniques psychologiques derrière les UGC ads qui convertissent, et comment vous y mettre.',
    excerpt: 'L’ère du scroll rapide exige des formats natifs. Décryptage des mécaniques psychologiques derrière les meilleures UGC ads.',
    lead: 'Vous avez un beau visuel produit. Fond propre, logo bien placé, promo en gros. Vous le lancez sur Meta ou TikTok… et il ne se passe pas grand-chose. Rassurez-vous, votre graphiste n’y est pour rien. Le problème, c’est que votre pub ressemble à une pub. Et sur un fil d’actu, c’est exactement ce que les gens ont appris à ignorer.',
    blocks: [
      { t: 'h2', x: 'Le problème n’est pas votre visuel. C’est le fil d’actu.' },
      { t: 'p', x: 'Faites l’expérience ce soir : ouvrez Instagram ou TikTok et observez votre propre pouce. Il décide en une fraction de seconde si un contenu mérite qu’on s’arrête. Et ce qui l’arrête, c’est rarement une affiche. C’est une tête, une voix, une situation qu’on reconnaît.' },
      { t: 'p', x: 'Les plateformes l’ont bien compris : leurs algorithmes favorisent les contenus qui retiennent l’attention. Une créa que personne ne regarde coûte plus cher à diffuser, touche moins de monde, et convertit moins. Le cercle vicieux est lancé.' },
      { t: 'p', x: 'C’est là que l’UGC entre en jeu.' },
      { t: 'h2', x: 'Une UGC ad, c’est quoi exactement ?' },
      { t: 'p', x: 'UGC veut dire « User Generated Content », contenu créé par les utilisateurs. En publicité, on parle d’UGC ads pour des vidéos (ou photos) qui ont le look d’un contenu fait par un vrai client : filmé au téléphone, face caméra, dans une vraie cuisine ou une vraie salle de bain, avec de vrais mots.' },
      { t: 'p', x: 'Attention, « qui a le look » ne veut pas dire « fait à l’arrache ». Les UGC qui marchent sont très travaillées : un script, un angle, une accroche testée. Elles ont juste l’air naturelles. C’est tout l’art.' },
      { t: 'h2', x: 'Les 4 mécaniques psychologiques derrière les UGC qui cartonnent' },
      { t: 'h3', x: '1. « C’est quelqu’un comme moi »' },
      { t: 'p', x: 'On fait davantage confiance à une personne qui nous ressemble qu’à une marque. Quand une maman de deux enfants explique comment elle s’organise le matin avec votre produit, les autres mamans ne voient pas une pub : elles voient une copine qui partage un bon plan.' },
      { t: 'h3', x: '2. La preuve sociale incarnée' },
      { t: 'p', x: 'Un avis 5 étoiles, c’est bien. Une personne qui raconte avec son visage et sa voix pourquoi elle a racheté votre produit, c’est beaucoup plus fort. La preuve devient concrète, crédible et mémorisable.' },
      { t: 'h3', x: '3. La boucle ouverte' },
      { t: 'p', x: '« Je ne pensais pas que ça changerait autant ma routine… » : notre cerveau déteste les histoires sans fin. Une bonne accroche ouvre une question, et le spectateur reste pour avoir la réponse. Ces premières secondes sont les plus importantes de toute la vidéo.' },
      { t: 'h3', x: '4. La démonstration qui rassure' },
      { t: 'p', x: 'Voir le produit utilisé pour de vrai, c’est répondre à la question que tout acheteur se pose : « est-ce que ça va marcher pour moi ? ». La démonstration réduit le risque perçu, et c’est souvent ce qui fait basculer un curieux en client.' },
      { t: 'cta', x: 'Vos créas actuelles tournent en rond ? Envoyez-nous 3 de vos pubs en cours : on vous dit gratuitement lesquelles garder, lesquelles couper, et quel angle UGC tester en premier.', label: 'Je demande mon avis créa' },
      { t: 'h2', x: 'L’anatomie d’une UGC qui convertit' },
      { t: 'table', head: ['Moment', 'Durée indicative', 'Rôle', 'Exemple'], rows: [
        ['L’accroche', '0 à 3 s', 'Arrêter le pouce', '« J’ai failli renvoyer ce produit. Heureusement que je ne l’ai pas fait. »'],
        ['Le problème', '3 à 8 s', 'Créer l’identification', '« Tous les matins, c’était la même galère… »'],
        ['La démonstration', '8 à 20 s', 'Prouver', 'Le produit en action, sans coupure trompeuse'],
        ['Le résultat', '20 à 25 s', 'Projeter', '« Maintenant, je gagne 10 minutes chaque matin. »'],
        ['L’appel à l’action', 'Fin', 'Déclencher', '« Le lien est juste en dessous, ils ont une offre cette semaine. »'],
      ] },
      { t: 'p', x: 'Les durées sont des repères, pas des règles. Sur TikTok, les formats plus longs fonctionnent aussi très bien, à condition que chaque seconde donne une raison de rester.' },
      { t: 'h2', x: 'Alors, le statique est mort ?' },
      { t: 'p', x: 'Non, et on vous le dit franchement. Les visuels statiques gardent de vrais usages :' },
      { t: 'ul', items: ['**Le reciblage** : quelqu’un qui connaît déjà votre marque n’a pas besoin d’une histoire, juste d’un rappel et d’une bonne raison d’acheter maintenant.', '**Les offres limitées** : soldes, code promo, livraison offerte. Un message simple, un visuel clair.', '**Le catalogue** : pour montrer beaucoup de produits rapidement.'] },
      { t: 'p', x: 'Le vrai problème, c’est de ne faire que du statique. Pour aller chercher de nouveaux clients, la vidéo native est devenue incontournable. La bonne stratégie, c’est un mix, testé et ajusté en permanence.' },
      { t: 'h2', x: 'Les erreurs qu’on voit (vraiment) tout le temps' },
      { t: 'ul', items: [
        '**Une accroche qui commence par le nom de la marque.** Personne ne s’arrête pour un logo.',
        '**Un créateur qui lit son script.** Ça se voit, et ça casse tout. Mieux vaut des points clés et de la spontanéité.',
        '**Une seule vidéo pour tout le monde.** Un même produit se vend avec des angles différents selon la cible : le prix, le gain de temps, le plaisir, la preuve.',
        '**Des tests sans hypothèse.** Tester 20 vidéos au hasard, c’est payer cher pour apprendre peu. Chaque test doit répondre à une question.',
        '**Des promesses qu’on ne peut pas tenir.** Un avant/après exagéré peut faire vendre une fois… et générer des retours, des avis négatifs et des refus de la plateforme.',
      ] },
      { t: 'baba', x: 'On l’a vécu : une vidéo filmée en 10 minutes dans une cuisine a battu une production à plusieurs milliers d’euros. Comme quoi, pas besoin de moyens hollywoodiens pour cartonner en créa. Ce qui compte, c’est l’accroche et la sincérité.' },
      { t: 'faq', items: [
        ['Faut-il payer des créateurs UGC ?', 'Souvent oui, et c’est normal : c’est un vrai travail. Vous pouvez aussi solliciter vos clients satisfaits ou vos équipes. Dans tous les cas, prévoyez un accord écrit sur l’utilisation des vidéos en publicité.'],
        ['Combien de vidéos faut-il pour démarrer ?', 'Pas besoin d’en avoir 50. Trois à cinq vidéos avec des angles bien différents suffisent pour un premier test sérieux. On affine ensuite avec ce qui marche.'],
        ['Est-ce que ça marche en B2B ?', 'Oui, sous une autre forme : témoignage client, démonstration par un expert, coulisses. Le principe reste le même : un humain qui parle à un humain.'],
        ['Vous pouvez nous aider à écrire les scripts ?', 'C’est même l’un de nos métiers. On écrit les angles et les scripts, on briefe les créateurs, et on pilote les tests. [Découvrir notre direction créative](/direction-creative-ia).'],
      ] },
    ],
    endCta: { title: 'Et si on regardait vos créas ensemble ?', text: 'En 30 minutes, on passe vos pubs actuelles en revue et on vous propose 3 angles UGC à tester. Pas de jargon, pas d’engagement : juste des idées concrètes que vous pouvez appliquer dès la semaine prochaine, avec ou sans nous.' },
    related: ['/direction-creative-ia', '/expertises/social-ads'],
  },
  {
    slug: 'audit-ia-claude-acquisition',
    category: 'IA & Automation',
    readTime: 5,
    date: '2026-01-28',
    title: 'IA × Acquisition : comment nous utilisons Claude pour pré-auditer vos comptes en 30 secondes',
    metaTitle: 'Comment nous utilisons Claude pour pré-auditer vos comptes Ads',
    description: 'En 30 secondes, l’IA repère ce qui cloche dans vos campagnes. Ensuite, c’est l’expert qui décide. Voici notre méthode, sans langue de bois.',
    excerpt: 'Notre méthode combine l’analyse IA instantanée et l’expertise terrain pour des diagnostics précis. L’IA repère, l’expert tranche.',
    lead: 'Oui, une IA peut lire des milliers de lignes de données publicitaires en quelques secondes et pointer ce qui cloche. Non, ça ne remplace pas un expert. On vous montre comment on combine les deux chez SEAD CONSEIL, et pourquoi c’est ce duo qui fait gagner du temps (et de l’argent) à nos clients.',
    blocks: [
      { t: 'h2', x: 'Le problème : un audit « à la main » prend des jours' },
      { t: 'p', x: 'Un compte Google Ads ou Meta Ads un peu actif, c’est vite des milliers de termes de recherche, des centaines de produits, des dizaines de campagnes, et des mois d’historique. Tout passer au peigne fin à la main prend des jours. Résultat : beaucoup d’audits se contentent de regarder les grandes lignes, et les vraies fuites de budget passent entre les mailles.' },
      { t: 'h2', x: 'Ce que Claude fait en 30 secondes' },
      { t: 'p', x: 'Claude est un assistant d’IA développé par la société Anthropic. On lui fournit des exports de vos données (jamais vos accès), et il nous livre en quelques secondes une première liste de points à creuser :' },
      { t: 'ul', items: [
        '**Les termes de recherche qui coûtent sans rien rapporter**, triés par argent dépensé.',
        '**Les produits qui aspirent le budget** sans générer de ventes, ou avec une rentabilité en chute.',
        '**Les campagnes qui se marchent dessus**, par exemple quand deux campagnes se disputent les mêmes recherches.',
        '**Les écarts bizarres d’une période à l’autre** : un coût qui grimpe, un taux de conversion qui s’effondre, une campagne qui change de comportement.',
        '**Les incohérences dans les conversions** : des chiffres trop beaux pour être vrais, des doublons possibles.',
      ] },
      { t: 'p', x: 'En clair : Claude fait le travail de tri qui prendrait une à deux journées à un humain, et nous tend une liste de pistes.' },
      { t: 'h2', x: 'Ce que Claude ne fait pas (et ne fera jamais à notre place)' },
      { t: 'ul', items: [
        '**Il ne connaît pas vos marges.** Un produit « rentable » pour Google peut vous faire perdre de l’argent une fois la livraison et le coût d’achat déduits.',
        '**Il ne connaît pas votre contexte.** Un pic de dépense peut être une erreur… ou votre lancement de gamme prévu depuis six mois.',
        '**Il peut se tromper.** Une IA peut mal interpréter une donnée ou affirmer quelque chose de faux avec aplomb. Chaque piste est donc vérifiée par un humain avant d’arriver chez vous.',
        '**Il ne décide pas.** Couper une campagne, déplacer du budget, relancer une gamme : ces choix engagent votre entreprise. Ils sont pris par un expert, avec vous.',
      ] },
      { t: 'cta', x: 'Curieux de savoir ce que ce pré-audit donnerait sur votre compte ? On le fait gratuitement, puis on vous explique les résultats en 30 minutes, avec un humain en face de vous.', label: 'Je veux mon pré-audit' },
      { t: 'h2', x: 'Notre méthode en 4 étapes' },
      { t: 'ol', items: [
        '**L’export.** Vous nous donnez un accès en lecture seule, ou vous nous envoyez des exports. Nous retirons les informations sensibles inutiles à l’analyse.',
        '**La passe IA.** Claude analyse les données et produit une liste d’anomalies et d’opportunités. Quelques secondes à quelques minutes selon la taille du compte.',
        '**La vérification experte.** On reprend chaque point, on le confronte à l’interface, à votre site, à votre historique. On écarte les fausses alertes, on creuse les vraies.',
        '**La restitution.** Un échange de 30 minutes, des priorités claires, et ce que chaque action peut vous rapporter.',
      ] },
      { t: 'p', x: 'Le vrai gain n’est pas de faire un audit en 30 secondes. C’est de passer notre temps sur ce qui compte : comprendre votre business et décider, au lieu de trier des tableaux.' },
      { t: 'h2', x: 'Et la confidentialité de mes données ?' },
      { t: 'p', x: 'Question légitime, et on préfère que vous la posiez. Nous ne demandons jamais d’accès administrateur pour un audit, nous limitons les données envoyées à ce qui est utile à l’analyse, et nous utilisons des outils professionnels dont les conditions encadrent l’usage des données. Si vous le souhaitez, nous signons un accord de confidentialité avant de commencer.' },
      { t: 'baba', x: 'Lors d’un audit, l’IA a repéré en quelques secondes une fuite de budget que personne n’avait vue depuis des mois : un produit phare, en rupture sur le site, continuait d’être promu dans une campagne Search. L’IA le classait simplement comme « peu performant ». C’est la vérification humaine qui a trouvé la vraie cause, et évité la mauvaise conclusion.' },
      { t: 'faq', items: [
        ['L’IA va-t-elle remplacer les agences ?', 'Elle remplace les tâches répétitives, pas le jugement. Une agence qui se contente d’appliquer des réglages a du souci à se faire. Une agence qui pilote votre rentabilité devient au contraire plus efficace.'],
        ['Puis-je faire la même chose moi-même avec une IA ?', 'Vous pouvez obtenir une première liste de pistes, oui. Le plus dur reste de savoir lesquelles sont vraies, lesquelles comptent, et quoi en faire. C’est précisément là qu’on intervient.'],
        ['Le pré-audit est-il vraiment gratuit ?', 'Oui. Vous repartez avec vos 3 priorités, que vous travailliez ensuite avec nous ou non. [Je réserve mon créneau](/audit-offert).'],
      ] },
    ],
    endCta: { title: 'L’IA trouve les pistes. On vous dit lesquelles suivre.', text: 'Envoyez-nous l’adresse de votre site et on s’occupe du reste. Sous 24 h ouvrées, un humain vous recontacte pour planifier la restitution.' },
    related: ['/methode', '/expertises/google-ads'],
  },
  {
    slug: 'meta-ads-2026-signaux-faibles',
    category: 'Meta Ads',
    readTime: 7,
    date: '2026-01-20',
    title: 'Meta Ads 2026 : les 5 signaux faibles à surveiller ce trimestre',
    metaTitle: 'Meta Ads 2026 : 5 signaux faibles à surveiller ce trimestre',
    description: 'Advantage+, Reels, API Conversions, diversité créative… Les changements discrets de Meta Ads qui pèsent sur vos performances, et quoi faire.',
    excerpt: 'Advantage+, Reels Ads, API Conversions… Les changements silencieux qui redéfinissent vos performances.',
    lead: 'Chez Meta, les gros changements font rarement la une. Ils arrivent par petites touches : un paramètre par défaut qui bouge, un format qui prend plus de place, une recommandation qui devient insistante. Pris un par un, ça ne paraît pas grand-chose. Mis bout à bout, ça peut faire varier vos résultats bien plus que vous ne l’imaginez. Voici les 5 signaux qu’on surveille de près pour nos clients.',
    blocks: [
      { t: 'note', x: 'Meta fait évoluer ses outils en permanence : les noms et la disponibilité des fonctionnalités peuvent changer d’un trimestre à l’autre. Nous mettons cet article à jour régulièrement.' },
      { t: 'h2', x: 'Signal n°1 : Advantage+ devient la norme, pas une option' },
      { t: 'p', x: 'Advantage+ Shopping était au départ un type de campagne à part. Meta pousse désormais la logique Advantage+ (ciblage, placements et créas automatisés) dans quasiment toutes les campagnes. Le paramétrage manuel existe encore, mais il devient l’exception.' },
      { t: 'p', x: '**Ce que ça change pour vous :** vous contrôlez de moins en moins qui voit vos pubs. Ce que vous contrôlez, ce sont les données que vous envoyez à Meta et les créas que vous lui donnez. Si ces deux éléments sont faibles, l’automatisation dépense vite… et mal.' },
      { t: 'p', x: '**Ce qu’on fait :** on garde une structure de compte simple, et on sépare clairement l’acquisition de nouveaux clients et le reciblage des clients existants, pour que l’algorithme ne se contente pas de « racheter » des ventes qui auraient eu lieu de toute façon.' },
      { t: 'h2', x: 'Signal n°2 : le vertical 9:16 prend toute la place' },
      { t: 'p', x: 'Reels, Stories, et le fil d’actu lui-même : l’inventaire publicitaire est de plus en plus vertical, plein écran, vidéo. Une créa pensée en carré ou en paysage, recadrée à la va-vite, perd en impact.' },
      { t: 'p', x: '**Ce qu’on fait :** chaque concept est décliné nativement en 9:16, avec les textes placés dans les zones qui ne sont pas masquées par l’interface. Et on fait de l’UGC : on vous en parle dans notre article sur les [UGC ads](/blog/ugc-ads-creas-statiques).' },
      { t: 'h2', x: 'Signal n°3 : la qualité de vos données de conversion fait la différence' },
      { t: 'p', x: 'Avec les restrictions de suivi dans les navigateurs et sur mobile, le pixel seul ne voit plus tout. L’API Conversions (qui envoie les événements directement depuis votre serveur ou votre plateforme e-commerce) est devenue indispensable. Et Meta attribue un score à la qualité de correspondance de vos événements.' },
      { t: 'p', x: '**Ce que ça change pour vous :** deux annonceurs avec les mêmes créas et le même budget peuvent obtenir des résultats très différents, simplement parce que l’un envoie des données plus complètes que l’autre.' },
      { t: 'p', x: '**Ce qu’on fait :** on vérifie que l’API Conversions est en place, que les événements ne sont pas comptés en double, et que les informations transmises sont suffisantes, dans le respect du consentement de vos visiteurs.' },
      { t: 'cta', x: 'Vous ne savez pas si votre API Conversions est bien configurée ? C’est souvent là que se cache le premier gain. On vérifie gratuitement.', label: 'Je fais vérifier mon compte Meta' },
      { t: 'h2', x: 'Signal n°4 : la diversité des créas devient un levier de ciblage' },
      { t: 'p', x: 'Meta a revu en profondeur la façon dont son système choisit quelle pub montrer à qui. Conséquence pratique : plusieurs variantes très proches d’une même pub sont traitées comme… une seule pub. Pour toucher des profils différents, il faut des créas vraiment différentes : un autre angle, une autre personne, un autre format.' },
      { t: 'p', x: '**Ce qu’on fait :** plutôt que 15 variantes de couleur de bouton, on produit 3 à 5 concepts franchement distincts (le prix, la preuve, l’émotion, l’usage, l’objection levée), et on les laisse trouver leur public.' },
      { t: 'h2', x: 'Signal n°5 : l’IA générative s’invite dans le Gestionnaire de publicités' },
      { t: 'p', x: 'Arrière-plans générés, textes proposés automatiquement, recadrages, variantes : Meta intègre de plus en plus d’outils de création automatique, parfois activés par défaut.' },
      { t: 'p', x: '**Ce que ça change pour vous :** c’est pratique pour aller vite, mais vous risquez de diffuser des éléments que personne n’a relus. Un texte approximatif, une image qui ne ressemble plus vraiment à votre produit, et c’est votre image de marque qui en pâtit.' },
      { t: 'p', x: '**Ce qu’on fait :** on active ces options au cas par cas, et on relit tout ce qui est diffusé. L’IA génère, on valide. C’est notre philosophie.' },
      { t: 'h2', x: 'Votre check-list du trimestre' },
      { t: 'ol', items: ['Vérifier que l’API Conversions est active et que les événements ne sont pas en double.', 'Contrôler les options de créas automatiques activées sur vos campagnes.', 'Faire l’inventaire de vos créas : avez-vous au moins 3 concepts vraiment différents ?', 'Vérifier que chaque concept existe en 9:16 natif.', 'Séparer la part du budget consacrée aux nouveaux clients et celle consacrée au reciblage.'] },
      { t: 'baba', x: 'Sur un compte, la simple correction de l’API Conversions a fait remonter 38 % de conversions en plus dans le Gestionnaire de publicités. Les ventes étaient déjà là : Meta ne les voyait pas. Avec des données complètes, l’algorithme a enfin pu optimiser sur la réalité.' },
      { t: 'faq', items: [
        ['Faut-il tout passer en Advantage+ ?', 'Pas forcément tout, pas forcément tout de suite. On teste d’abord sur une partie du budget, en comparant avec votre structure actuelle, avant de généraliser.'],
        ['Combien de créas faut-il renouveler par mois ?', 'Ça dépend de votre budget et de la vitesse à laquelle vos pubs s’essoufflent. Pour la plupart des comptes, quelques nouveaux concepts par mois suffisent, à condition qu’ils soient vraiment différents.'],
        ['Vous gérez aussi TikTok et Snapchat ?', 'Oui, et les mêmes principes s’appliquent : données propres, créas natives et diversité des angles. [Découvrir notre offre Social Ads](/expertises/social-ads).'],
      ] },
    ],
    endCta: { title: 'Vos résultats Meta ont bougé sans raison apparente ?', text: 'C’est souvent l’un de ces 5 signaux. Réservez 30 minutes avec nous : on regarde votre compte, on identifie ce qui a changé, et on vous dit quoi faire en priorité.' },
    related: ['/expertises/social-ads', '/blog/ugc-ads-creas-statiques'],
  },
];
