// Articles réécrits pour les redirections 301 des anciennes URL WordPress.
export const ARTICLES_C = [
  {
    slug: 'google-ads-ia-evolutions',
    category: 'Google Ads',
    readTime: 7,
    date: '2026-09-25',
    title: 'Google Ads et IA en 2026 : ce qui change vraiment pour les annonceurs',
    metaTitle: 'Google Ads et IA en 2026 : ce qui change pour les annonceurs',
    description: 'Enchères automatiques, Performance Max, AI Max, annonces générées : ce que l’IA change dans Google Ads, et ce qu’elle ne fera jamais à votre place.',
    excerpt: 'Enchères, ciblage, annonces : l’IA décide de plus en plus de choses dans Google Ads. Ce qui a changé, et où l’humain reste indispensable.',
    lead: 'En quelques années, Google Ads est passé d’un outil qu’on réglait mot-clé par mot-clé à une machine largement pilotée par l’intelligence artificielle. Enchères, ciblage, annonces : l’IA décide de plus en plus de choses. Bonne nouvelle, elle est très efficace. Mauvaise nouvelle, elle est aussi très efficace quand on lui donne le mauvais objectif. Voici ce qui a changé, et où l’humain reste indispensable.',
    blocks: [
      { t: 'note', x: 'Les fonctionnalités de Google Ads évoluent vite et leur disponibilité varie selon les pays. Cet article est mis à jour régulièrement.' },
      { t: 'h2', x: 'Les enchères : l’automatisation est devenue la norme' },
      { t: 'p', x: 'Les stratégies d’enchères automatiques (maximiser les conversions, CPA cible, ROAS cible) sont aujourd’hui le réglage par défaut de la plupart des campagnes. À chaque enchère, l’algorithme tient compte de signaux qu’aucun humain ne peut traiter en temps réel : appareil, moment de la journée, localisation, et bien d’autres.' },
      { t: 'p', x: 'Ce que cela change pour vous : le travail ne consiste plus à ajuster des enchères à la main, mais à donner à l’algorithme le bon objectif et les bonnes données. Si votre suivi des conversions compte deux fois certaines ventes, ou si votre objectif de ROAS ne tient pas compte de vos marges, l’IA optimisera parfaitement… un chiffre faux.' },
      { t: 'h2', x: 'Le ciblage : des mots-clés aux intentions' },
      { t: 'p', x: 'Avec la requête large et les campagnes Performance Max, Google ne se contente plus de faire correspondre des mots : il interprète l’intention derrière la recherche. AI Max pour les campagnes Search pousse encore cette logique, en élargissant automatiquement les requêtes couvertes et en adaptant les annonces.' },
      { t: 'p', x: 'Cette extension du ciblage peut faire découvrir des requêtes rentables auxquelles personne n’avait pensé. Elle peut aussi dépenser sur des recherches sans rapport avec votre offre. D’où l’importance de lire régulièrement les termes de recherche et de tenir à jour vos listes de mots-clés négatifs.' },
      { t: 'h2', x: 'Performance Max : plus de puissance, un peu plus de transparence' },
      { t: 'p', x: 'Performance Max diffuse vos annonces sur l’ensemble des réseaux de Google (Search, Shopping, YouTube, Display, Gmail, Discover, Maps) à partir d’une seule campagne. Longtemps critiquée pour son côté « boîte noire », elle offre désormais davantage de rapports et de leviers de contrôle, comme des exclusions plus fines et une meilleure lecture de la répartition par réseau.' },
      { t: 'p', x: 'Notre constat de terrain : Performance Max donne de très bons résultats quand les produits sont segmentés selon leur rentabilité réelle. Sans segmentation, elle concentre souvent le budget sur quelques produits qui vendent beaucoup mais rapportent peu.' },
      { t: 'h2', x: 'Les annonces générées par l’IA' },
      { t: 'p', x: 'Google propose de générer automatiquement titres, descriptions et visuels à partir de votre site. Pour un compte qui démarre, c’est un vrai gain de temps. Mais une annonce générée reprend ce qui est déjà écrit sur votre site, et ressemble souvent à celles de vos concurrents, qui utilisent le même outil.' },
      { t: 'p', x: 'La valeur ajoutée humaine se situe dans l’argument : ce qui vous différencie vraiment, la preuve qui rassure, l’offre qui déclenche le clic. L’IA décline ; elle n’invente pas votre avantage concurrentiel.' },
      { t: 'h2', x: 'Les données : le nouveau nerf de la guerre' },
      { t: 'p', x: 'Plus Google automatise, plus la qualité des données qu’on lui fournit devient décisive. En Europe, cela passe notamment par un bandeau de consentement correctement configuré avec le mode consentement de Google, par les conversions améliorées et, pour l’e-commerce, par un flux produits propre et complet dans Merchant Center.' },
      { t: 'p', x: 'Dans la plupart des audits que nous réalisons, le premier gain ne vient pas d’un réglage de campagne, mais d’une correction du suivi des conversions.' },
      { t: 'baba', x: 'Sur un compte e-commerce que nous pilotons, seules 690 des 1 000 déclinaisons les plus rentables de l’année précédente l’étaient encore un an plus tard. Les campagnes continuaient pourtant à pousser les anciens best-sellers, parce que c’est ce qu’on leur avait demandé. L’IA ne remet pas en cause ses consignes : c’est notre travail de les actualiser.' },
      { t: 'h2', x: 'Ce que l’IA ne fera jamais à votre place' },
      { t: 'ul', items: ['**Connaître vos marges.** Google voit un chiffre d’affaires ; il ne sait pas combien vous gagnez sur chaque produit.', '**Arbitrer entre vos priorités.** Écouler un stock, lancer une gamme, protéger une marque : ce sont des décisions d’entreprise.', '**Vérifier que les chiffres sont justes.** Un algorithme ne remet pas en cause les données qu’il reçoit.', '**Expliquer.** Votre direction veut savoir pourquoi le coût a augmenté ; « l’algorithme a décidé » n’est pas une réponse.'] },
      { t: 'h2', x: 'Par où commencer ?' },
      { t: 'ol', items: ['Vérifiez votre suivi des conversions : chaque vente est-elle comptée une fois, et une seule ?', 'Définissez un objectif de rentabilité qui tient compte de vos marges, pas seulement de votre chiffre d’affaires.', 'Lisez vos termes de recherche des 30 derniers jours et excluez ce qui n’a rien à faire là.', 'Segmentez vos produits selon leur rentabilité dans Shopping et Performance Max.'] },
      { t: 'cta', x: 'Vous voulez un regard extérieur sur votre compte ? On vous dit en 30 minutes où agir en premier.', label: 'Demander mon audit offert' },
      { t: 'faq', items: [
        ['Faut-il encore un expert pour gérer Google Ads ?', 'Oui, mais son rôle a changé : moins de réglages manuels, plus de stratégie, de contrôle des données et de pilotage par la rentabilité.'],
        ['Les enchères automatiques sont-elles adaptées aux petits budgets ?', 'Elles ont besoin d’un volume minimal de conversions pour apprendre. Avec très peu de conversions, une stratégie plus simple ou un objectif intermédiaire est souvent préférable au départ.'],
        ['Performance Max remplace-t-elle les campagnes Search ?', 'Pas nécessairement. Beaucoup de comptes gagnent à combiner Performance Max et des campagnes Search ciblées, notamment pour garder la main sur les requêtes de marque et les requêtes les plus stratégiques.'],
      ] },
    ],
    endCta: { title: 'L’IA accélère. Encore faut-il lui donner le bon cap.', text: 'Réservez 30 minutes avec nous : on regarde vos objectifs, votre suivi des conversions et vos campagnes, et on vous donne 3 priorités concrètes.' },
    related: ['/expertises/google-ads', '/blog/budget-ads-methode-allocation'],
  },
  {
    slug: 'ia-creas-publicitaires',
    category: 'Créa & contenus',
    readTime: 6,
    date: '2026-09-18',
    title: 'IA et créas publicitaires : ce que l’outil fait, ce que l’humain décide',
    metaTitle: 'IA et créas publicitaires : ce que l’outil fait, ce que l’humain décide',
    description: 'Génération de visuels, variantes à grande échelle, scripts UGC : comment l’IA transforme la créa publicitaire, et pourquoi le regard humain reste décisif.',
    excerpt: 'L’IA produit cent variantes en une heure. Elle rend d’autant plus précieux ce qu’elle ne sait pas faire : avoir une idée qui touche juste.',
    lead: 'Il y a quelques années, produire dix variantes d’une publicité demandait une semaine et un graphiste. Aujourd’hui, l’IA en produit cent en une heure. Cette abondance change profondément la façon de travailler la créa publicitaire. Elle rend aussi plus précieux que jamais ce que l’IA ne sait pas faire : avoir une idée qui touche juste.',
    blocks: [
      { t: 'h2', x: 'Pourquoi la créa est devenue le premier levier de ciblage' },
      { t: 'p', x: 'Sur Meta, TikTok et de plus en plus sur Google, les options de ciblage manuel se sont réduites au profit de l’automatisation. Les plateformes trouvent elles-mêmes les personnes susceptibles de réagir. Et le principal signal qu’elles utilisent pour cela, c’est la créa : qui s’arrête, qui regarde, qui clique.' },
      { t: 'p', x: 'Autrement dit, une créa pensée pour les jeunes parents sera progressivement montrée à de jeunes parents. Le message est devenu le ciblage.' },
      { t: 'h2', x: 'Ce que l’IA fait très bien' },
      { t: 'ul', items: ['**Décliner** : adapter un visuel à tous les formats (carré, vertical, bannière) en quelques secondes.', '**Varier** : proposer des dizaines de titres, d’accroches ou de fonds pour les tests.', '**Accélérer** : produire un premier jet de script, un storyboard, une maquette.', '**Analyser** : repérer, dans les résultats, les éléments communs aux créas qui performent.'] },
      { t: 'h2', x: 'Ce que l’IA fait mal (ou pas du tout)' },
      { t: 'ul', items: ['**Trouver l’insight.** L’objection que votre client n’ose pas formuler, la phrase qu’il emploie vraiment : cela s’apprend en écoutant des clients, pas en générant du texte.', '**Garder une marque cohérente.** Cent variantes produites sans cadre finissent par ne plus ressembler à rien, ni à personne.', '**Juger ce qui est acceptable.** Une affirmation non prouvée, une image trompeuse, une promesse de santé : l’IA ne voit pas le risque juridique ou réputationnel.', '**Décider quoi tester.** Tester cent variantes au hasard coûte cher et n’apprend rien. Un bon test part d’une hypothèse.'] },
      { t: 'h2', x: 'Notre méthode en 4 étapes' },
      { t: 'ol', items: ['**L’insight d’abord** : avis clients, questions au service client, termes de recherche. Nous cherchons les mots exacts de vos clients.', '**Les angles** : 3 à 5 angles publicitaires distincts (le prix, la preuve, l’émotion, l’usage, l’objection levée).', '**La production assistée** : l’IA décline chaque angle en scripts, accroches et formats, que nous sélectionnons et retravaillons.', '**Le test avec hypothèse** : on teste un angle contre un autre, pas une couleur de bouton contre une autre. Le résultat nous apprend quelque chose sur vos clients.'] },
      { t: 'baba', x: 'Les meilleures accroches que j’ai vues ne sortaient pas d’un outil : elles sortaient d’avis clients. Sur une campagne TikTok, ce sont les vidéos « problème / solution », écrites avec les mots des clients, qui ont porté les résultats. L’IA nous a aidés à les décliner ; elle ne les aurait pas trouvées seule.' },
      { t: 'h2', x: 'Le cas particulier des scripts UGC' },
      { t: 'p', x: 'Les vidéos au format UGC (contenu qui ressemble à celui d’un utilisateur, filmé au téléphone) fonctionnent particulièrement bien sur les réseaux sociaux, parce qu’elles ressemblent à ce qu’on y regarde déjà. Leur structure est simple : une accroche dans les premières secondes, une démonstration ou une preuve, un appel à l’action. [Lire notre article sur les UGC ads](/blog/ugc-ads-creas-statiques).' },
      { t: 'p', x: 'L’IA peut écrire des dizaines de scripts de ce type. Mais c’est la personne à l’écran, sa sincérité et sa façon de parler, qui fait qu’on y croit. Un script parfait lu sans conviction ne convertit pas.' },
      { t: 'h2', x: 'Transparence : faut-il dire qu’une créa est générée par IA ?' },
      { t: 'p', x: 'Les règles des plateformes et la réglementation européenne évoluent vers davantage de transparence sur les contenus générés ou modifiés par l’IA, en particulier lorsqu’ils représentent des personnes réelles ou des situations réalistes. Au-delà de l’obligation, c’est une question de confiance : un client qui se sent trompé par une image ne revient pas. Sur notre propre site, les illustrations réalisées avec l’IA sont signalées comme telles.' },
      { t: 'cta', x: 'Vous voulez un regard neuf sur vos créas ? On vous propose 3 angles à tester, gratuitement.', label: 'Réserver mon audit offert' },
      { t: 'faq', items: [
        ['Peut-on faire toutes ses créas avec l’IA ?', 'Techniquement, oui. En pratique, les meilleures performances viennent d’un mélange : des contenus réels (produits, personnes, clients) et des déclinaisons assistées par l’IA.'],
        ['Combien de créas faut-il tester ?', 'Moins qu’on ne le pense, mais régulièrement. Quelques angles bien distincts, renouvelés dès que les performances s’essoufflent, valent mieux que des dizaines de variantes quasi identiques.'],
      ] },
    ],
    endCta: { title: 'L’IA génère. On choisit ce qui mérite d’être diffusé.', text: 'Parlons de vos créas actuelles et de ce que vos clients disent vraiment de vous : c’est là que se cachent vos prochaines accroches.' },
    related: ['/direction-creative-ia', '/expertises/copywriting-contenus-ia'],
  },
];
