// Article 01 (carte mise en avant du blog).
export const ARTICLES_D = [
  {
    slug: 'performance-max-guide-scaler-roas',
    category: 'Google Ads',
    readTime: 9,
    date: '2026-02-12',
    featured: true,
    title: 'Performance Max : le guide ultime pour scaler sans perdre en ROAS',
    metaTitle: 'Performance Max : scaler sans perdre en ROAS (guide 2026)',
    description: 'Mesure, segmentation par rentabilité, exclusions, paliers de budget : comment structurer vos campagnes Performance Max pour grandir sans sacrifier votre marge.',
    excerpt: 'Comment structurer vos campagnes PMax pour maximiser le profit réel tout en gardant le contrôle sur l’algorithme Google.',
    lead: 'Performance Max, c’est un peu comme une voiture de course sans volant : ça va très vite, mais pas forcément là où vous voulez aller. Dès qu’on augmente le budget, le ROAS a tendance à plonger, et on ne sait pas trop pourquoi. Bonne nouvelle : ce n’est pas une fatalité. Voici la méthode qu’on applique sur les comptes que nous pilotons, des e-commerces à quelques centaines de produits jusqu’aux catalogues de plusieurs milliers de références.',
    blocks: [
      { t: 'h2', x: 'Performance Max, en deux mots' },
      { t: 'p', x: 'Performance Max (PMax pour les intimes) diffuse vos annonces sur tout l’inventaire de Google à partir d’une seule campagne : Search, Shopping, YouTube, Display, Discover, Gmail et Maps. Vous fournissez un objectif, un budget, des produits et des éléments créatifs ; l’IA de Google décide du reste : où diffuser, à qui, à quel prix.' },
      { t: 'p', x: 'C’est redoutablement efficace pour trouver des ventes. C’est aussi redoutablement efficace pour dépenser votre budget sur ce qui ne vous rapporte rien, si personne ne tient le volant.' },
      { t: 'h2', x: 'Pourquoi le ROAS chute quand on augmente le budget' },
      { t: 'ul', items: [
        '**L’algorithme pousse ce qu’il connaît.** Il concentre le budget sur les produits qui ont vendu hier, même si ce ne sont plus ceux qui rapportent aujourd’hui.',
        '**Les premiers euros sont les meilleurs.** Plus vous montez le budget, plus Google va chercher des clients éloignés, sur des réseaux moins qualifiés (Display, YouTube, Discover).',
        '**Il capte des ventes déjà acquises.** Sans exclusions, PMax adore les recherches sur votre marque : des ventes qui auraient eu lieu de toute façon.',
        '**Les déclinaisons se font concurrence.** Google choisit seul quelle couleur ou quelle contenance mettre en avant, et ce n’est pas toujours la plus rentable.',
      ] },
      { t: 'p', x: 'Aucun de ces problèmes ne se règle avec un « bon réglage » caché. Ils se règlent avec une structure.' },
      { t: 'h2', x: 'Étape 1 : fiabiliser la mesure avant tout' },
      { t: 'p', x: 'PMax optimise vers le chiffre que vous lui donnez. Si ce chiffre est faux, tout le reste l’est aussi. Avant de toucher au budget, on vérifie :' },
      { t: 'ul', items: [
        'que chaque vente est comptée une fois, et une seule (pas de doublon entre balise Google Ads et import GA4) ;',
        'que la valeur remontée est la bonne (hors taxes ou TTC, mais toujours la même logique) ;',
        'que le mode consentement et les conversions améliorées sont en place, pour ne pas piloter à moitié aveugle ;',
        'que l’objectif de ROAS tient compte de votre marge, pas seulement de votre chiffre d’affaires.',
      ] },
      { t: 'p', x: 'Sur plusieurs comptes, ce seul chantier a changé davantage les résultats que n’importe quelle optimisation de campagne.' },
      { t: 'h2', x: 'Étape 2 : segmenter vos produits par rentabilité' },
      { t: 'p', x: 'C’est le cœur de la méthode. Au lieu d’une seule campagne « tous produits », on répartit le catalogue en groupes qui n’ont pas le même niveau d’exigence. Voici la grille qu’on utilise, à adapter à vos marges :' },
      { t: 'table', head: ['Groupe', 'ROAS observé', 'Ce qu’on fait'], rows: [
        ['Best', 'Supérieur à 5', 'Budget protégé, objectif de ROAS maintenu'],
        ['Classic', 'Entre 2 et 5', 'Objectif de ROAS relevé progressivement, par petits paliers'],
        ['À surveiller', 'Entre 1 et 2', 'Objectif de ROAS nettement relevé, budget plafonné'],
        ['À sortir', 'Inférieur à 1', 'Exclusion, ou campagne test à petit budget et durée limitée'],
      ] },
      { t: 'p', x: 'Concrètement, on utilise les **libellés personnalisés** du flux Merchant Center pour classer chaque produit, puis une campagne (ou un groupe d’éléments) par groupe. Et surtout, on **actualise ces libellés régulièrement**, au moins tous les trois mois, sur la valeur ET le ROAS des six derniers mois. Pas seulement sur le volume.' },
      { t: 'p', x: 'Pourquoi c’est si important ? Parce que vos best-sellers changent. Sur le compte d’[AnoX](/cas-clients/anox), seules **690 des 1 000 déclinaisons les plus rentables de 2025 l’étaient encore en 2026**. Les 310 sorties du classement coûtaient encore 690 k€ sur le semestre, alors que les 310 nouvelles entrées généraient 5,26 M€ de valeur de conversion pour 1,6 M€ de coût. Un filtre « Best » figé, c’est du budget qui part au mauvais endroit.' },
      { t: 'p', x: 'Autre exemple, chez [AnoY](/cas-clients/anoy) : le produit le plus rentable en publicité dispose de sa propre campagne PMax, séparée d’une campagne « reste performant » et d’une campagne « reste non performant », chacune avec son objectif.' },
      { t: 'cta', x: 'Vous voulez savoir comment votre catalogue se répartit entre Best, Classic et produits à sortir ? On fait l’exercice avec vous pendant l’audit offert.', label: 'Je veux mon audit PMax' },
      { t: 'h2', x: 'Étape 3 : garder la main sur le trafic' },
      { t: 'p', x: 'PMax n’est plus la boîte noire de ses débuts. Google a ouvert plusieurs leviers de contrôle, qu’on active systématiquement :' },
      { t: 'ul', items: [
        '**Les exclusions de mots-clés au niveau du compte**, pour écarter le trafic hors sujet ou peu qualifié.',
        '**Les exclusions de marque**, pour éviter que PMax ne s’attribue les recherches sur votre nom, qu’une campagne Search dédiée gère mieux et moins cher.',
        '**La lecture par réseau** : les rapports permettent désormais de voir la part de Display, YouTube ou Discover. Si ces réseaux consomment beaucoup sans convertir, on ajuste les éléments créatifs et la structure.',
        '**Le rapport sur les termes de recherche**, qu’on lit comme pour une campagne Search classique.',
      ] },
      { t: 'h2', x: 'Étape 4 : dompter les déclinaisons gourmandes' },
      { t: 'p', x: 'C’est le piège le plus sous-estimé. Google choisit seul la déclinaison qu’il met en avant, et une couleur peut capter l’essentiel des clics d’un produit sans en être la plus rentable. Sur un compte que nous pilotons, une seule couleur d’un produit phare est passée de 90 à près de 340 000 clics en un an, pour un ROAS de 2,3, bien en dessous des autres coloris.' },
      { t: 'p', x: '**Ce qu’on fait :** on regroupe les déclinaisons par performance et on exclut celles qui consomment sans convertir. Même logique pour les gammes en lancement : budget de test plafonné et durée définie à l’avance.' },
      { t: 'h2', x: 'Étape 5 : scaler par paliers, pas d’un coup' },
      { t: 'p', x: 'Doubler le budget du jour au lendemain, c’est relancer l’apprentissage de l’algorithme et accepter quelques semaines de ROAS en dents de scie. On préfère :' },
      { t: 'ol', items: [
        'augmenter le budget par paliers réguliers sur les campagnes Best et Classic uniquement ;',
        'surveiller le rendement du dernier euro dépensé, pas la moyenne ;',
        'relever l’objectif de ROAS sur les groupes moins rentables au lieu de leur donner plus de budget ;',
        'caler la diffusion sur la saison : un produit d’été continuera de capter des clics en hiver si on ne lui dit rien.',
      ] },
      { t: 'p', x: 'C’est cette discipline qui a permis au compte d’AnoX de faire passer son ROAS Shopping de 2,88 à 3,23 entre le premier semestre 2025 et le premier semestre 2026, tout en générant 35 % de clics supplémentaires.' },
      { t: 'h2', x: 'Étape 6 : nourrir l’algorithme avec de bons éléments' },
      { t: 'p', x: 'PMax ne vaut que ce que vous lui donnez à diffuser. Un flux produits propre (titres explicites, attributs complets, images de qualité), des visuels et des vidéos pensés pour chaque réseau, des titres d’annonce qui mettent en avant vos vrais arguments. Si vous ne fournissez pas de vidéo, Google en fabriquera une à partir de vos images. Rarement flatteur.' },
      { t: 'baba', x: 'La plupart des comptes PMax que nous auditons n’ont pas un problème d’algorithme, ils ont un problème de consignes. On a demandé à Google de pousser les best-sellers d’il y a un an, et il le fait très bien. Notre travail, c’est de mettre ses consignes à jour, tous les trimestres, avec vos marges sous les yeux.' },
      { t: 'note', x: 'Clients anonymisés. Pour AnoX, les montants et volumes cités ont été multipliés par un coefficient identique afin de préserver son anonymat ; les ratios (ROAS, évolutions en %) sont réels.' },
      { t: 'h2', x: 'Votre check-list Performance Max' },
      { t: 'ol', items: [
        'Suivi des conversions vérifié : pas de doublon, bonne valeur, consentement en place.',
        'Catalogue segmenté par rentabilité, avec des libellés actualisés au moins chaque trimestre.',
        'Exclusions de mots-clés et de marque actives au niveau du compte.',
        'Répartition par réseau contrôlée chaque mois.',
        'Déclinaisons gourmandes identifiées et regroupées.',
        'Budget augmenté par paliers, sur les groupes rentables uniquement.',
      ] },
      { t: 'faq', items: [
        ['Faut-il garder des campagnes Shopping classiques à côté de PMax ?', 'Ça dépend du compte. Une campagne Shopping standard peut servir de filet de sécurité ou de terrain de test pour certains produits. On décide au cas par cas, après l’audit.'],
        ['Combien de campagnes PMax faut-il ?', 'Assez pour séparer des produits qui n’ont pas le même niveau de rentabilité, pas davantage. Trop de campagnes dispersent les données et ralentissent l’apprentissage.'],
        ['PMax convient-elle aux petits budgets ?', 'Oui, à condition d’avoir assez de conversions pour que l’algorithme apprenne. Avec peu de ventes, on commence souvent par une structure plus simple et un objectif moins exigeant.'],
        ['Vous pouvez auditer nos campagnes PMax ?', 'C’est même l’un des audits qu’on fait le plus. [Réservez votre créneau](/audit-offert) : vous repartez avec vos 3 priorités.'],
      ] },
    ],
    endCta: { title: 'Votre PMax dépense-t-elle au bon endroit ?', text: 'En 30 minutes, on regarde votre suivi des conversions, la segmentation de votre catalogue et la répartition par réseau, et on vous dit où agir en premier. Gratuit et sans engagement.' },
    related: ['/expertises/google-ads', '/blog/budget-ads-methode-allocation', '/cas-clients/anox'],
  },
];
