// Articles 05 et 06 (cartes existantes du blog).
export const ARTICLES_B = [
  {
    slug: 'budget-ads-methode-allocation',
    category: 'Stratégie',
    readTime: 9,
    date: '2026-01-14',
    title: 'Budget Ads : la méthode SEAD pour allouer sans gaspiller',
    metaTitle: 'Budget Ads : notre méthode pour allouer sans gaspiller',
    description: 'MER, marge, profit incrémental : la méthode SEAD pour répartir votre budget publicitaire entre les canaux et arrêter de financer des ventes déjà acquises.',
    excerpt: 'Notre méthode de répartition budgétaire basée sur le MER et le profit incrémental, appliquée à des comptes de plusieurs millions d’euros de dépenses annuelles.',
    lead: '« On met combien sur Google, combien sur Meta, combien sur TikTok ? » C’est la question qu’on nous pose le plus souvent. Et la réponse la plus fréquente sur le marché, c’est : « on met plus là où le ROAS est le meilleur ». Sauf que ce raisonnement, en apparence logique, fait gaspiller beaucoup d’argent. Voici comment on s’y prend chez SEAD CONSEIL, sur des comptes qui vont de quelques milliers à plusieurs millions d’euros de dépenses par an.',
    blocks: [
      { t: 'h2', x: 'Pourquoi le ROAS de chaque plateforme vous ment (un peu)' },
      { t: 'p', x: 'Chaque plateforme mesure ses propres résultats. Et chacune a tendance à s’attribuer un maximum de ventes. Un client voit votre pub sur Instagram, cherche votre marque sur Google, puis achète : Meta et Google peuvent tous les deux compter cette vente. Additionnez les ventes déclarées par chaque plateforme, et vous obtenez souvent plus que votre chiffre d’affaires réel.' },
      { t: 'p', x: 'Autre piège : une partie des ventes attribuées à la pub auraient eu lieu de toute façon. Vos clients fidèles qui tapent votre nom sur Google, par exemple. Les compter comme des victoires publicitaires, c’est se raconter une jolie histoire.' },
      { t: 'h2', x: 'Nos 3 indicateurs de référence' },
      { t: 'h3', x: '1. Le MER, votre boussole' },
      { t: 'p', x: 'Le MER (Marketing Efficiency Ratio) est tout simple : votre chiffre d’affaires total divisé par vos dépenses marketing totales, toutes plateformes confondues. Il ne dit pas quelle plateforme fait quoi, mais il dit la vérité sur l’ensemble. Si vos plateformes affichent toutes de super résultats et que votre MER baisse, il y a un problème.' },
      { t: 'h3', x: '2. La marge, pas le chiffre d’affaires' },
      { t: 'p', x: 'Un ROAS de 4 sur un produit à 20 % de marge vous fait perdre de l’argent. Le même ROAS sur un produit à 60 % de marge est excellent. On calcule donc un seuil de rentabilité par produit ou par famille, à partir de votre marge réelle (après coût d’achat, livraison, retours et frais de paiement).' },
      { t: 'h3', x: '3. Le profit incrémental' },
      { t: 'p', x: 'La vraie question n’est pas « combien cette campagne a-t-elle généré ? » mais « combien de ventes en plus avons-nous faites grâce à elle ? ». C’est ce qu’on appelle l’incrémentalité. Elle se mesure avec des tests : couper une campagne sur une zone géographique et comparer, utiliser les outils de mesure d’impact proposés par les plateformes, ou observer ce qui se passe quand on met en pause un canal.' },
      { t: 'cta', x: 'Vous ne connaissez pas votre MER, ou vous n’êtes pas sûr de votre seuil de rentabilité ? On le calcule avec vous pendant l’audit offert, à partir de vos vrais chiffres.', label: 'Je calcule mon seuil avec vous' },
      { t: 'h2', x: 'La méthode SEAD en 5 étapes' },
      { t: 'h3', x: 'Étape 1 : fixer le plancher de rentabilité' },
      { t: 'p', x: 'À partir de vos marges, on calcule le MER minimum en dessous duquel la publicité vous fait perdre de l’argent. C’est la ligne rouge de tout le reste.' },
      { t: 'h3', x: 'Étape 2 : répartir le budget en trois poches' },
      { t: 'table', head: ['Poche', 'Part indicative', 'Contenu', 'Objectif'], rows: [
        ['Socle', '≈ 70 %', 'Les campagnes et produits qui ont prouvé leur rentabilité', 'Sécuriser le profit'],
        ['Croissance', '≈ 20 %', 'Ce qui marche mais n’est pas encore au maximum : nouveaux produits, nouveaux pays, nouvelles audiences', 'Faire grandir'],
        ['Test', '≈ 10 %', 'Nouveaux canaux, nouveaux formats, nouveaux angles créatifs', 'Apprendre'],
      ] },
      { t: 'p', x: 'Ces proportions sont un point de départ : un compte en lancement aura une poche test plus grosse, un compte en phase de rentabilité une poche socle plus importante.' },
      { t: 'h3', x: 'Étape 3 : surveiller le rendement du dernier euro' },
      { t: 'p', x: 'Sur chaque campagne, les premiers euros sont les plus rentables. Plus on augmente le budget, plus on va chercher des clients difficiles à convaincre, et plus chaque vente coûte cher. On surveille donc le rendement du dernier euro dépensé, pas la moyenne. Quand il passe sous votre plancher, on arrête d’augmenter.' },
      { t: 'h3', x: 'Étape 4 : tester l’incrémentalité régulièrement' },
      { t: 'p', x: 'Au moins une fois par trimestre, on teste un canal ou une campagne importante pour vérifier qu’elle apporte vraiment des ventes supplémentaires. Les campagnes sur votre propre marque et le reciblage sont souvent les premiers suspects.' },
      { t: 'h3', x: 'Étape 5 : réallouer chaque semaine, décider chaque mois' },
      { t: 'p', x: 'Les petits ajustements se font chaque semaine, selon les résultats. Les grands arbitrages (ouvrir un canal, en fermer un, changer la répartition des poches) se décident une fois par mois, avec vous.' },
      { t: 'h2', x: 'Un exemple pour y voir plus clair' },
      { t: 'p', x: '**Exemple fictif, pour illustrer la méthode.** Une marque e-commerce dépense 30 000 € par mois et réalise 150 000 € de chiffre d’affaires : son MER est de 5. Sa marge après coûts variables est de 40 %. Chaque euro de chiffre d’affaires lui laisse donc 0,40 €, et elle a besoin d’un MER d’au moins 2,5 pour ne pas perdre d’argent sur la publicité. Avec un MER de 5, elle a de la marge pour grandir : on peut augmenter le budget progressivement tant que le rendement du dernier euro reste au-dessus du plancher.' },
      { t: 'p', x: 'Mais en regardant de plus près, on découvre que 30 % du budget va à des campagnes sur sa propre marque et à du reciblage de clients déjà acquis. Après un test, on constate qu’une bonne partie de ces ventes aurait eu lieu sans pub. On réduit ces campagnes, et on réinvestit l’argent économisé dans la poche croissance.' },
      { t: 'h2', x: 'Et dans la vraie vie ?' },
      { t: 'p', x: 'Sur le compte d’[AnoX](/cas-clients/anox), cette logique nous a permis d’identifier, sur un seul semestre, plus d’1 M€ de dépenses Shopping à un ROAS inférieur à 1, tandis que les produits réellement rentables avaient changé d’une année sur l’autre. Le plan d’action qui en découle : moins de budget sur ce qui ne vend plus, plus d’exigence sur ce qui vend. (Montants modifiés par un coefficient pour préserver l’anonymat du client ; les ratios sont réels.)' },
      { t: 'baba', x: 'Un client a découvert qu’une partie de son budget finançait des ventes déjà acquises : des clients fidèles qui l’auraient retrouvé de toute façon. Pourquoi payer pour une fidélité déjà gagnée ? Cet argent-là est bien plus utile pour aller chercher de nouveaux clients.' },
      { t: 'faq', items: [
        ['Quel budget minimum pour appliquer cette méthode ?', 'La logique fonctionne à toutes les échelles. Avec un petit budget, on se concentre sur un ou deux canaux et on simplifie les tests. Le principe reste le même : piloter par la marge.'],
        ['J’ai besoin de quels chiffres pour démarrer ?', 'Votre chiffre d’affaires, vos dépenses publicitaires par canal et une estimation de votre marge par produit ou par famille. Si vous ne l’avez pas, on vous aide à la calculer.'],
        ['Et si mes plateformes affichent de bons résultats mais que mon chiffre ne décolle pas ?', 'C’est exactement le cas où le MER et les tests d’incrémentalité sont utiles. [Parlons de votre situation](/audit-offert).'],
      ] },
    ],
    endCta: { title: 'Votre budget travaille-t-il vraiment pour votre profit ?', text: 'Lors de l’audit offert, on calcule votre plancher de rentabilité, on repère les dépenses qui financent des ventes déjà acquises, et on vous propose une première répartition. En 30 minutes, avec vos vrais chiffres.' },
    related: ['/expertises/google-ads', '/methode'],
  },
  {
    slug: 'tiktok-ads-etude-de-cas-dnvb',
    category: 'Case Study',
    readTime: 8,
    date: '2026-01-06',
    title: 'TikTok Ads : de 0 à 100 k€/mois en 90 jours — étude de cas',
    metaTitle: 'TikTok Ads : de 0 à 100 k€/mois en 90 jours — étude de cas',
    description: 'Comment nous avons accompagné une DNVB française dans le lancement de ses campagnes TikTok : méthode, créas, erreurs et résultats (ROAS moyen 4,2).',
    excerpt: 'Comment nous avons accompagné une DNVB française dans son lancement sur TikTok, avec un ROAS moyen de 4,2 sur la période.',
    lead: 'Quand cette marque nous a contactés, TikTok n’était pour elle qu’une application que ses clients utilisaient… sans jamais y voir ses produits. Trois mois plus tard, la plateforme générait environ 100 k€ de chiffre d’affaires par mois et était devenue un vrai canal d’acquisition de nouveaux clients. Voici comment on a fait, étape par étape, avec les réussites, mais aussi les ratés.',
    blocks: [
      { t: 'h2', x: 'Le contexte' },
      { t: 'table', head: ['Élément', 'Détail'], rows: [
        ['Le client', 'AnoW, une DNVB française (marque vendue en direct en ligne), anonymisée à sa demande'],
        ['Le point de départ', 'Une acquisition concentrée sur un seul réseau social, avec des coûts en hausse, et aucune présence publicitaire sur TikTok'],
        ['L’objectif', 'Ouvrir un nouveau canal d’acquisition rentable, avec un objectif de rentabilité fixé avant le lancement'],
        ['Durée', '90 jours'],
        ['Notre rôle', 'Stratégie, direction créative, pilotage des campagnes, reporting hebdomadaire'],
      ] },
      { t: 'h2', x: 'Pourquoi TikTok ?' },
      { t: 'p', x: 'On ne pousse pas TikTok à tout le monde. Ici, trois éléments nous ont convaincus : le public cible de la marque était très présent sur la plateforme, les produits se prêtaient naturellement à la démonstration en vidéo, et la marque avait déjà des clients prêts à parler d’elle. Sans ces conditions, on lui aurait conseillé autre chose.' },
      { t: 'h2', x: 'Phase 1 (jours 1 à 30) : tester, tester, tester' },
      { t: 'p', x: 'Premier mois : l’objectif n’était pas de vendre à tout prix, mais d’apprendre vite ce qui marchait. Nous avons :' },
      { t: 'ul', items: [
        'mis en place le suivi des conversions (pixel et API des événements) et vérifié qu’il remontait les bonnes ventes ;',
        'défini plusieurs angles publicitaires différents à partir des avis clients et des questions reçues par le service client ;',
        'produit une première série de vidéos UGC avec plusieurs créateurs, en format natif TikTok ;',
        'lancé des campagnes de test avec un budget volontairement limité.',
      ] },
      { t: 'p', x: '**Ce qui a marché :** les UGC « problème / solution », où une vraie personne expose un souci du quotidien puis montre comment le produit le règle. **Ce qui n’a pas marché :** l’unboxing. Le packaging n’était pas la valeur ajoutée du produit, et les vidéos ne donnaient aucune raison d’acheter. On le raconte parce qu’un test raté qui apprend quelque chose, c’est aussi un résultat.' },
      { t: 'h2', x: 'Phase 2 (jours 31 à 60) : structurer et accélérer' },
      { t: 'p', x: 'Une fois les angles gagnants identifiés, on a :' },
      { t: 'ul', items: [
        'regroupé les créas performantes dans une structure de campagne plus simple, pour laisser l’algorithme apprendre ;',
        'augmenté le budget par paliers hebdomadaires, en surveillant le rendement du dernier euro dépensé ;',
        'décliné les vidéos gagnantes avec de nouvelles accroches et de nouveaux créateurs, pour éviter l’usure.',
      ] },
      { t: 'cta', x: 'Vous vous demandez si TikTok peut marcher pour votre marque ? Avant de dépenser le moindre euro, on vous dit franchement si c’est une bonne idée, et comment on s’y prendrait.', label: 'J’en parle avec l’équipe' },
      { t: 'h2', x: 'Phase 3 (jours 61 à 90) : industrialiser sans perdre en rentabilité' },
      { t: 'p', x: 'Le plus dur n’est pas de réussir une campagne, c’est de tenir dans la durée. Dernier mois, on a :' },
      { t: 'ul', items: [
        'mis en place un rythme de production créative régulier, avec de nouvelles vidéos chaque semaine ;',
        'croisé les résultats TikTok avec les ventes réelles de la marque, pour vérifier que la croissance venait bien de nouveaux clients et pas d’un simple transfert depuis d’autres canaux.',
      ] },
      { t: 'h2', x: 'Les résultats' },
      { t: 'table', head: ['Indicateur', 'Jour 1', 'Jour 90'], rows: [
        ['Chiffre d’affaires mensuel attribué à TikTok', '0 €', '≈ 100 000 €'],
        ['ROAS moyen sur la période (mesure TikTok Ads)', '—', '4,2'],
        ['Coût par acquisition', '—', '12 €'],
        ['Part de nouveaux clients', '—', '68 %'],
      ] },
      { t: 'p', x: 'Le résultat le plus précieux n’est pas le ROAS, c’est la part de nouveaux clients : plus des deux tiers des acheteurs venus de TikTok ne connaissaient pas la marque. C’est exactement ce qu’on cherchait en ouvrant un nouveau canal.' },
      { t: 'h2', x: 'Ce qu’on en retient (et ce qui peut vous servir)' },
      { t: 'ol', items: [
        '**La créa fait le ciblage.** Sur TikTok, ce sont les vidéos qui trouvent le public, pas les réglages d’audience.',
        '**Les avis clients sont une mine d’or.** Les meilleures accroches venaient des mots exacts des clients.',
        '**On monte le budget par paliers.** Doubler du jour au lendemain casse souvent la rentabilité.',
        '**On vérifie avec les vraies ventes.** Les chiffres de la plateforme sont un indicateur, pas la vérité.',
      ] },
      { t: 'faq', items: [
        ['Faut-il un gros budget pour démarrer sur TikTok ?', 'Non. Le premier mois sert à tester avec un budget maîtrisé. On n’augmente que quand on sait ce qui marche.'],
        ['Ces résultats sont-ils reproductibles pour ma marque ?', 'Chaque marque est différente, et on ne promet pas de chiffres à l’avance. Ce qui est reproductible, c’est la méthode : tester vite, garder ce qui marche, monter par paliers et vérifier avec les vraies ventes.'],
        ['Vous gérez la production des vidéos ?', 'On écrit les angles et les scripts, on briefe et on sélectionne les créateurs, et on pilote les tests. [Découvrir notre direction créative](/direction-creative-ia).'],
      ] },
      { t: 'note', x: 'Résultats obtenus pour ce client, sur cette période, et présentés avec son accord. Le ROAS est celui mesuré par TikTok Ads. Chaque marque est différente : ces chiffres ne constituent pas une promesse de résultat.' },
    ],
    endCta: { title: 'Votre marque pourrait-elle être la prochaine étude de cas ?', text: 'En 30 minutes, on regarde vos canaux actuels, vos produits et vos créas, et on vous dit si TikTok (ou un autre levier) a du sens pour vous, avec un plan de départ réaliste. Gratuit et sans engagement.' },
    related: ['/expertises/social-ads', '/direction-creative-ia'],
  },
];
