// Cas clients anonymisés (AnoW, AnoX, AnoY, AnoZ). Les vrais noms n’apparaissent que dans les références (SITE.clients).
// Cas clients présentés avec l’accord des clients. Chiffres issus des données Google Ads / TikTok Ads des comptes.
export const CASES = [
  {
    slug: 'anox',
    client: 'AnoX',
    sector: 'E-commerce B2C et B2B · produits techniques pour le bâtiment et la rénovation',
    levers: ['Google Ads', 'Shopping', 'Performance Max', 'Multi-pays'],
    title: 'AnoX : un ROAS Shopping en hausse sur un compte multi-pays',
    metaTitle: 'Cas client AnoX : ROAS Shopping de 2,88 à 3,23 | SEAD CONSEIL',
    description: 'Comment nous pilotons chaque semaine les campagnes Google Ads d’un e-commerçant sur 5 marchés européens : ROAS Shopping de 2,88 à 3,23, +35 % de clics, CPC −9 %.',
    summary: 'ROAS Shopping de 2,88 à 3,23 entre le S1 2025 et le S1 2026, avec 35 % de clics en plus.',
    kpis: [['2,88 → 3,23', 'ROAS Shopping, S1 2025 → S1 2026'], ['+35 %', 'de clics Shopping'], ['−9 %', 'de coût par clic Shopping']],
    blocks: [
      { t: 'h2', x: 'Le contexte' },
      { t: 'p', x: 'AnoX vend en ligne des produits techniques pour le bâtiment et la rénovation, à des particuliers comme à des professionnels. Le compte Google Ads couvre cinq marchés européens, avec une offre dédiée aux pros et un budget publicitaire de plusieurs dizaines de millions d’euros par an.' },
      { t: 'p', x: 'Le défi : des milliers de produits et de déclinaisons (couleurs, contenances), une forte saisonnalité, et des algorithmes Shopping et Performance Max qui ont tendance à pousser ce qui a vendu hier, pas forcément ce qui rapporte aujourd’hui.' },
      { t: 'h2', x: 'Ce que nous faisons' },
      { t: 'ol', items: [
        '**Un reporting hebdomadaire, compte par compte.** Chaque marché est analysé isolément : clics, taux de clic, ROAS. Une bonne semaine, c’est plus de clics et un meilleur taux de clic ; une mauvaise, les deux qui reculent.',
        '**Une lecture produit par produit.** Nous suivons quelles déclinaisons restent rentables d’une année sur l’autre. En 2026, seules 690 des 1 000 déclinaisons les plus rentables de 2025 l’étaient encore. Les 310 nouvelles entrées ont généré 5,26 M€ de valeur de conversion pour 1,6 M€ de coût (ROAS 3,3).',
        '**La relance d’une gamme.** Une gamme saisonnière a été relancée en septembre 2025 avec un suivi dédié.',
        '**Un plan d’action trimestriel.** Pour le quatrième trimestre 2026 : actualiser les filtres « Best », sortir les déclinaisons sans conversion, relever l’exigence de ROAS par palier et caler la diffusion sur la saison.',
      ] },
      { t: 'h2', x: 'Les résultats' },
      { t: 'table', head: ['Indicateur (Google Ads, Shopping)', 'S1 2025', 'S1 2026'], rows: [
        ['ROAS', '2,88', '3,23'],
        ['Clics', 'base 100', '135'],
        ['Coût par clic', 'base 100', '91'],
      ] },
      { t: 'p', x: 'Le compte a gagné en rentabilité tout en augmentant son trafic. Cette marge de manœuvre permet aujourd’hui d’être plus exigeant sur les produits peu rentables sans décrocher sur le chiffre d’affaires.' },
      { t: 'h2', x: 'Le rôle de l’IA, le rôle de l’humain' },
      { t: 'p', x: 'L’IA nous aide à passer au crible des milliers de déclinaisons en quelques minutes. Mais c’est la lecture humaine qui fait la différence : repérer qu’un best-seller d’été va continuer à capter des clics en hiver, ou qu’une couleur aspire le budget d’un produit sans en être la plus rentable.' },
      { t: 'note', x: 'Chiffres : données Google Ads du client, 1er janvier – 30 juin 2026 comparé à la même période de 2025. Le ROAS correspond à la valeur de conversion divisée par le coût. Pour préserver l’anonymat du client, les montants et volumes (euros, clics, nombre de produits) ont été multipliés par un coefficient identique. Les ratios (ROAS, évolutions en %) sont les valeurs réelles.' },
    ],
  },
  {
    slug: 'anoy',
    client: 'AnoY',
    sector: 'E-commerce · compléments alimentaires',
    levers: ['Google Ads', 'Performance Max', 'SEO', 'Shopify'],
    title: 'AnoY : croiser Google Ads, SEO et ventes pour savoir ce qui rapporte vraiment',
    metaTitle: 'Cas client AnoY : Google Ads, SEO et Shopify croisés | SEAD CONSEIL',
    description: 'Comment nous croisons les données Google Ads, Search Console et Shopify d’un e-commerçant en compléments alimentaires pour concentrer le budget sur les produits rentables.',
    summary: 'Une lecture croisée publicité, référencement naturel et ventes pour concentrer le budget sur les produits rentables.',
    kpis: [['3 sources', 'Google Ads, Search Console, Shopify'], ['1 produit phare', 'isolé dans sa propre campagne'], ['3 pays', 'France, puis Espagne et Italie']],
    blocks: [
      { t: 'h2', x: 'Le contexte' },
      { t: 'p', x: 'AnoY vend des compléments alimentaires en ligne, en France et avec une expansion vers l’Espagne et l’Italie. Comme beaucoup d’e-commerçants, la marque voyait des chiffres différents selon l’outil consulté : Google Ads, Shopify et la Search Console ne racontaient pas tout à fait la même histoire.' },
      { t: 'h2', x: 'Ce que nous faisons' },
      { t: 'ol', items: [
        '**Croiser les trois sources.** Ventes Google Ads par produit, tableau de bord Shopify et requêtes Search Console, pour distinguer ce que la publicité apporte vraiment de ce que le référencement naturel apporte déjà.',
        '**Restructurer Performance Max autour de la rentabilité.** Le produit le plus rentable en publicité dispose de sa propre campagne ; les autres produits sont séparés entre « performants » et « non performants », avec des objectifs différents.',
        '**Protéger la marque et les requêtes clés.** Campagnes Search dédiées à la marque et à la catégorie principale, pour garder la main sur les recherches les plus stratégiques.',
        '**Livrer des analyses lisibles.** Des documents illustrés, avec des recommandations priorisées, plutôt que des tableaux de bord bruts.',
      ] },
      { t: 'h2', x: 'Ce que ça change' },
      { t: 'p', x: 'L’équipe sait désormais quels produits méritent un investissement publicitaire, lesquels se vendent déjà très bien en référencement naturel, et où arbitrer le budget avant d’ouvrir de nouveaux pays. Les décisions ne reposent plus sur un seul outil, mais sur une lecture croisée.' },
      { t: 'h2', x: 'Le rôle de l’IA, le rôle de l’humain' },
      { t: 'p', x: 'L’IA accélère le rapprochement de milliers de lignes issues de trois outils différents. L’humain vérifie les écarts, comprend pourquoi ils existent et en tire des décisions de budget.' },
      { t: 'note', x: 'Client anonymisé à sa demande.' },
    ],
  },
  {
    slug: 'anoz',
    client: 'AnoZ',
    sector: 'E-commerce · produits pour événements familiaux',
    levers: ['Google Ads', 'Search', 'Shopping', 'Performance Max', 'Demand Gen'],
    title: 'AnoZ : lire les termes de recherche pour passer la basse saison',
    metaTitle: 'Cas client AnoZ : analyse des recherches et saisonnalité | SEAD CONSEIL',
    description: 'Comment l’analyse annuelle des termes de recherche guide les campagnes Google Ads d’un e-commerçant très saisonnier, du pic des événements à la basse saison.',
    summary: 'Une analyse annuelle des recherches pour repérer les thèmes qui montent et soutenir les ventes hors saison.',
    kpis: [['Année N vs N-1', 'comparatif des termes de recherche'], ['5 types', 'de campagnes pilotées'], ['Basse saison', 'plan d’action dédié']],
    blocks: [
      { t: 'h2', x: 'Le contexte' },
      { t: 'p', x: 'AnoZ vend en ligne des produits pour les événements familiaux (mariages, baptêmes, communions). L’activité est très saisonnière : la demande explose au printemps et en été, puis retombe. Le compte combine Performance Max, Search, une campagne marque, Shopping et Demand Gen.' },
      { t: 'h2', x: 'Ce que nous faisons' },
      { t: 'ol', items: [
        '**Comparer les recherches d’une année sur l’autre.** Nous analysons les termes de recherche réels sur une période donnée et sur la même période de l’année précédente.',
        '**Repérer les thèmes qui montent et ceux qui reculent.** Types d’événements, couleurs, formats, requêtes de marque : chaque tendance devient une décision (renforcer, créer, exclure).',
        '**Préparer la basse saison.** Des recommandations pour maintenir les ventes quand la demande naturelle baisse, plutôt que de subir le creux.',
      ] },
      { t: 'h2', x: 'Ce que ça change' },
      { t: 'p', x: 'Le budget suit l’évolution réelle de la demande, et non l’historique du compte. Les nouveaux usages sont repérés tôt, et les dépenses sur des recherches qui ne convertissent plus sont coupées.' },
      { t: 'h2', x: 'Le rôle de l’IA, le rôle de l’humain' },
      { t: 'p', x: 'L’IA classe des milliers de requêtes par thème en quelques minutes. L’humain sait qu’une hausse de recherches en septembre prépare souvent les commandes de l’année suivante, et ajuste le calendrier en conséquence.' },
      { t: 'note', x: 'Client anonymisé à sa demande.' },
    ],
  },
  {
    slug: 'dnvb-tiktok-ads',
    client: 'AnoW',
    sector: 'E-commerce · DNVB française',
    levers: ['TikTok Ads', 'UGC', 'Direction créative'],
    title: 'AnoW : de 0 à 100 k€ de chiffre d’affaires mensuel sur TikTok en 90 jours',
    sector2: 'DNVB française',
    summary: 'ROAS moyen de 4,2 mesuré par TikTok Ads, CPA de 12 € et 68 % de nouveaux clients.',
    kpis: [['≈ 100 k€', 'de CA mensuel attribué à TikTok au 90e jour'], ['4,2', 'ROAS moyen sur la période'], ['68 %', 'de nouveaux clients']],
    href: '/blog/tiktok-ads-etude-de-cas-dnvb',
  },
];

export const getCase = (slug) => CASES.find((c) => c.slug === slug && c.blocks);
