import { IMAGES } from './site';

// Pages services. Chaque entrée alimente /expertises/[slug] (ou /direction-creative-ia).
export const SERVICES = {
  'google-ads': {
    path: '/expertises/google-ads',
    short: 'Google Ads',
    card: 'Search, Shopping, Performance Max. Des campagnes structurées autour de votre marge réelle, pas du seul ROAS affiché.',
    title: 'Agence Google Ads e-commerce et B2B pilotée par la marge | SEAD CONSEIL',
    description: 'Audit et gestion de vos campagnes Search, Shopping et Performance Max par un expert Google Ads. Objectif : votre marge, pas seulement le ROAS.',
    h1: 'Google Ads : des campagnes pilotées par votre marge',
    intro: 'Google Ads peut devenir votre canal le plus rentable, ou votre plus gros poste de dépense sans contrôle. La différence tient rarement à un réglage caché : elle tient aux objectifs qu’on donne aux algorithmes et à la qualité des données qu’on leur fournit.',
    image: IMAGES.conseil,
    blocks: [
      { t: 'h2', x: 'Ce que nous prenons en charge' },
      { t: 'h3', x: 'Search' },
      { t: 'p', x: 'Structure des campagnes, requêtes réelles, mots-clés négatifs, annonces et extensions. Nous lisons les termes de recherche un par un là où c’est utile, parce que c’est là que se cachent les fuites de budget.' },
      { t: 'h3', x: 'Shopping et Performance Max' },
      { t: 'p', x: 'Segmentation des produits selon leur rentabilité, optimisation du flux Merchant Center, choix des produits à pousser ou à couper. Nous suivons les produits qui restent rentables d’une année sur l’autre, et ceux qui ne le sont plus.' },
      { t: 'h3', x: 'Mesure et suivi des conversions' },
      { t: 'p', x: 'Balises, conversions améliorées, mode consentement : sans données fiables, les enchères automatiques optimisent à l’aveugle. C’est le premier point que nous vérifions.' },
      { t: 'h3', x: 'International' },
      { t: 'p', x: 'Pilotage multi-pays et multilingue (France, Espagne, Italie, Benelux…), avec une lecture pays par pays des coûts et des marges.' },
      { t: 'h2', x: 'Pourquoi un pilotage humain, à l’heure de l’IA ?' },
      { t: 'p', x: 'Les outils d’automatisation de Google sont puissants, et nous les utilisons. Mais ils ne connaissent ni vos marges, ni vos stocks, ni vos priorités commerciales. Nous traduisons ces réalités en objectifs que l’algorithme peut suivre, puis nous vérifions chaque semaine qu’il les suit vraiment.' },
      { t: 'h2', x: 'Comment se passe un accompagnement' },
      { t: 'ol', items: ['Audit du compte (accès en lecture) et restitution en visio.', 'Plan d’action priorisé : gains rapides d’abord, chantiers de fond ensuite.', 'Mise en œuvre par nos soins ou par votre équipe.', 'Point hebdomadaire : actions, résultats, prochaines étapes.'] },
      { t: 'h2', x: 'Étude de cas : AnoX' },
      { t: 'p', x: 'Sur un compte e-commerce présent sur 5 marchés européens, le ROAS Shopping est passé de **2,88 à 3,23** entre le premier semestre 2025 et le premier semestre 2026, avec **35 % de clics Shopping en plus** et un CPC en **baisse de 9 %**. [Lire le cas complet](/cas-clients/anox)' },
      { t: 'cta', x: 'Vous voulez savoir où votre compte Google Ads perd de l’argent ? On regarde ensemble, gratuitement.', label: 'Réserver mon audit offert' },
      { t: 'faq', title: 'Questions fréquentes sur la gestion Google Ads', items: [
        ['Performance Max est-elle adaptée à mon activité ?', 'Souvent, à condition de bien la cadrer : groupes de produits segmentés, signaux d’audience pertinents, exclusions et objectifs de rentabilité réalistes. Nous vérifions d’abord que votre suivi des conversions est fiable.'],
        ['Quel budget minimum pour Google Ads ?', 'Il dépend de votre secteur et du coût des clics. Nous vous donnons une estimation lors de l’audit, à partir de vos données réelles.'],
        ['Reprenez-vous un compte géré par une autre agence ?', 'Oui. Nous faisons un audit complet avant toute modification, pour ne rien casser de ce qui fonctionne.'],
      ] },
      { t: 'p', x: 'À lire aussi : [Performance Max : le guide pour scaler sans perdre en ROAS](/blog/performance-max-guide-scaler-roas) · [Google Ads et IA en 2026 : ce qui change vraiment](/blog/google-ads-ia-evolutions) · [Budget Ads : notre méthode pour allouer sans gaspiller](/blog/budget-ads-methode-allocation)' },
    ],
  },
  'social-ads': {
    path: '/expertises/social-ads',
    short: 'Social Ads',
    card: 'Meta, TikTok, Snapchat. Des audiences, des créas et des tests pensés pour vendre, pas seulement pour faire des vues.',
    title: 'Agence Meta Ads et TikTok Ads orientée performance | SEAD CONSEIL',
    description: 'Campagnes Meta, TikTok et Snapchat pilotées par un expert : audiences, créas et tests pensés pour vendre. Audit offert.',
    h1: 'Social Ads : Meta, TikTok et Snapchat, pilotés pour vendre',
    intro: 'Sur les réseaux sociaux, le ciblage s’est largement automatisé. Ce qui fait la différence aujourd’hui, c’est la créa : le message, le format, les trois premières secondes. Nous pilotons les deux ensemble.',
    image: IMAGES.crea,
    blocks: [
      { t: 'h2', x: 'Nos interventions' },
      { t: 'h3', x: 'Stratégie et structure de compte' },
      { t: 'p', x: 'Objectifs de campagne alignés sur votre rentabilité, structure simple qui laisse l’algorithme apprendre, budgets répartis entre prospection et reciblage.' },
      { t: 'h3', x: 'Créas et tests' },
      { t: 'p', x: 'Angles publicitaires, scripts UGC, déclinaisons de formats. Chaque créa est testée avec une hypothèse claire, pour savoir pourquoi elle marche, pas seulement si elle marche.' },
      { t: 'h3', x: 'Mesure' },
      { t: 'p', x: 'Pixel, API Conversions, attribution : nous comparons ce que dit la plateforme à ce que dit votre chiffre d’affaires réel.' },
      { t: 'h2', x: 'Quelle plateforme pour quelle entreprise ?' },
      { t: 'table', head: ['Plateforme', 'Particulièrement adaptée pour'], rows: [
        ['Meta (Facebook, Instagram)', 'E-commerce, génération de leads, reciblage, la plupart des audiences adultes'],
        ['TikTok', 'Produits visuels et démonstratifs, audiences jeunes, contenus natifs de type UGC'],
        ['Snapchat', 'Audiences 15-34 ans, notoriété et lancements'],
      ] },
      { t: 'h2', x: 'Étude de cas : AnoW, une DNVB française sur TikTok' },
      { t: 'p', x: 'En 90 jours, une marque qui n’avait jamais diffusé sur TikTok a atteint environ **100 k€ de chiffre d’affaires mensuel attribué à la plateforme**, avec un ROAS moyen de **4,2** mesuré par TikTok Ads et **68 % de nouveaux clients**. [Lire l’étude de cas](/blog/tiktok-ads-etude-de-cas-dnvb)' },
      { t: 'cta', x: 'Vos résultats Meta ou TikTok stagnent ? On passe vos campagnes et vos créas en revue, gratuitement.', label: 'Réserver mon audit offert' },
      { t: 'faq', items: [
        ['Faut-il produire beaucoup de vidéos ?', 'Il faut surtout produire régulièrement. Nous vous aidons à définir un rythme réaliste et à tirer plusieurs déclinaisons de chaque tournage.'],
        ['Gérez-vous aussi les publications organiques ?', 'Notre cœur de métier est la publicité. Nous pouvons cadrer la ligne éditoriale organique et la production de contenus dans le cadre de notre offre [Copywriting & contenus](/expertises/copywriting-contenus-ia).'],
      ] },
      { t: 'p', x: 'À lire aussi : [UGC Ads : pourquoi vos créas statiques ne convertissent plus](/blog/ugc-ads-creas-statiques) · [Meta Ads 2026 : les 5 signaux faibles](/blog/meta-ads-2026-signaux-faibles)' },
    ],
  },
  'copywriting-contenus-ia': {
    path: '/expertises/copywriting-contenus-ia',
    short: 'Copywriting & contenus IA',
    card: 'Annonces, fiches produits, pages, emails. L’IA produit du volume ; nous gardons votre voix et vos arguments.',
    title: 'Copywriting et contenus avec l’IA, relus par des experts | SEAD CONSEIL',
    description: 'Annonces, fiches produits, pages, emails et articles produits avec l’IA et affinés par un humain. Votre voix de marque, à grande échelle.',
    h1: 'Copywriting et contenus : l’IA pour le volume, l’humain pour la voix',
    intro: 'Tout le monde peut désormais générer mille textes en une minute. C’est justement pour ça que les textes génériques ne fonctionnent plus. Nous utilisons l’IA pour produire vite, et notre expérience pour que chaque texte sonne comme vous et donne une raison d’acheter.',
    image: IMAGES.crea,
    blocks: [
      { t: 'h2', x: 'Ce que nous écrivons' },
      { t: 'ul', items: ['**Annonces publicitaires** Google Ads et Social Ads, déclinées pour les tests.', '**Fiches produits et flux** : titres et descriptions optimisés pour Shopping et pour le référencement.', '**Pages de destination** : structure, arguments, réassurance, appels à l’action.', '**Emails et séquences** : accueil, relance panier, fidélisation.', '**Articles de blog** optimisés SEO, signés et relus.'] },
      { t: 'h2', x: 'Notre façon de travailler avec l’IA' },
      { t: 'ol', items: ['**Le brief humain** : vos clients, vos arguments, vos mots interdits, votre ton.', '**La production assistée** : l’IA génère des premières versions et des variantes, à partir de ce brief.', '**La réécriture experte** : nous sélectionnons, corrigeons, vérifions chaque affirmation et ajustons le ton.', '**Le test** : en publicité, ce sont les chiffres qui tranchent entre deux versions.'] },
      { t: 'h2', x: 'Ce que nous ne faisons pas' },
      { t: 'p', x: 'Nous ne publions pas de texte généré sans relecture, nous n’inventons pas d’avis clients et nous n’affirmons rien que vous ne puissiez prouver. C’est une question d’éthique, et c’est aussi ce qui protège votre marque.' },
      { t: 'cta', x: 'Envie de textes qui vous ressemblent, en plus grand nombre ? Parlons de votre ton et de vos priorités.', label: 'Réserver un échange' },
      { t: 'faq', items: [
        ['Google pénalise-t-il les contenus écrits avec l’IA ?', 'Google évalue l’utilité et la qualité d’un contenu, pas l’outil qui a servi à l’écrire. Un contenu produit en masse sans valeur ajoutée pose problème ; un contenu utile, exact et relu, non.'],
        ['Pouvez-vous reprendre notre ton actuel ?', 'Oui. Nous partons de vos meilleurs textes existants pour établir un guide de ton, que nous appliquons ensuite à chaque production.'],
      ] },
      { t: 'p', x: 'À lire aussi : [IA et créas publicitaires : ce que l’outil fait, ce que l’humain décide](/blog/ia-creas-publicitaires)' },
    ],
  },
  'direction-creative-ia': {
    path: '/direction-creative-ia',
    short: 'Direction créative IA',
    card: 'Scripts UGC, angles publicitaires, déclinaisons visuelles. La créa est devenue le premier levier de ciblage.',
    title: 'Direction créative publicitaire et scripts UGC assistés par l’IA | SEAD CONSEIL',
    description: 'Angles publicitaires, scripts UGC et déclinaisons visuelles : la créa est devenue le premier levier de ciblage. Méthode et retours de terrain.',
    h1: 'Direction créative : l’IA génère, nous choisissons',
    intro: 'Sur Meta, TikTok et de plus en plus sur Google, les algorithmes trouvent l’audience à partir de la créa elle-même. Une bonne créa ne se contente plus d’être belle : elle doit parler à la bonne personne dès la première seconde.',
    image: IMAGES.crea,
    blocks: [
      { t: 'h2', x: 'Ce que nous produisons' },
      { t: 'ul', items: ['Angles publicitaires construits à partir des vraies objections de vos clients.', 'Scripts UGC courts (accroche, preuve, appel à l’action), prêts à tourner.', 'Déclinaisons de visuels et de formats pour les tests.', 'Plan de test créatif : quoi tester, dans quel ordre, avec quel critère de décision.'] },
      { t: 'h2', x: 'Ce que nos tests nous ont appris' },
      { t: 'table', head: ['Ce qu’on pensait', 'Ce que le test a montré', 'Ce qu’on en retient'], rows: [
        ['Une production vidéo soignée convertit mieux', 'Une vidéo filmée en 10 minutes dans une cuisine a battu une production à plusieurs milliers d’euros', 'L’authenticité et l’accroche comptent plus que le budget de tournage'],
        ['L’unboxing met le produit en valeur', 'Sur une DNVB, l’unboxing a fait un flop : le packaging n’était pas la valeur ajoutée', 'On montre ce qui fait acheter, pas ce qui fait joli'],
        ['Il faut beaucoup de variantes', 'Les formats « problème / solution » ont porté les résultats, loin devant les variantes cosmétiques', 'Peu d’angles, mais vraiment différents'],
      ] },
      { t: 'cta', x: 'Envoyez-nous 3 de vos pubs en cours : on vous dit lesquelles garder, lesquelles couper, et quel angle tester en premier.', label: 'Je demande mon avis créa' },
      { t: 'faq', items: [
        ['Travaillez-vous avec des créateurs UGC ?', 'Oui. Nous écrivons les angles et les scripts, nous briefons et sélectionnons les créateurs, puis nous pilotons les tests.'],
        ['Utilisez-vous des images générées par IA ?', 'Pour des déclinaisons et des maquettes, oui, et nous le disons. Pour montrer un produit, une personne ou un résultat, nous privilégions le réel.'],
      ] },
      { t: 'p', x: 'À lire aussi : [UGC Ads : pourquoi vos créas statiques ne convertissent plus](/blog/ugc-ads-creas-statiques) · [Étude de cas TikTok Ads](/blog/tiktok-ads-etude-de-cas-dnvb)' },
    ],
  },
};

export const SERVICE_LIST = ['google-ads', 'social-ads', 'copywriting-contenus-ia', 'direction-creative-ia'].map((k) => ({ key: k, ...SERVICES[k] }));
